global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#anton_emelianov'

